PO Financing/Controllers/ApplicationController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.Extensions.Logging;
using PO_Financing.BusinessLogic;
using PO_Financing.Data;
using PO_Financing.Enums;
using PO_Financing.Helper;
using PO_Financing.Models;
using PO_Financing.ViewModels;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace PO_Financing.Controllers
{
    
    public class ApplicationController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IUserDataManagement _users;
        private readonly ApplicationDbContext _dbContext;
        private readonly IPurchaseOrdersManagement _poManager;
        private readonly IWalletManagement _walletManager;

        public ApplicationController(ILogger<HomeController> logger, IUserDataManagement users, ApplicationDbContext dbContext, IPurchaseOrdersManagement poManager, IWalletManagement walletManager)
        {
            _logger = logger;
            _users = users;
            _dbContext = dbContext;
            _poManager = poManager;
            _walletManager = walletManager;
        }

        public IActionResult Apply()
        {
            if (User.Identity.Name == null)
            {
                return RedirectToAction("Login", "Account");
            }
            return View();
        }

        public async Task<IActionResult> CreateApplication(PurchaseOrderApplicationViewModel purchaseOrderApplication)
        {
            IDbContextTransaction transaction = _dbContext.Database.BeginTransaction();
            try
            {
                var userId = (await _users.GetUserByEmail(User.Identity.Name)).Id;
                purchaseOrderApplication.Status = PurchaseOrderStatus.Pending.GetDisplayName();
                purchaseOrderApplication.UserId = userId;

                var application = ViewModelBuilder.PurchaseOrderApplicationModel(purchaseOrderApplication);
                var userWalletVm = ViewModelBuilder.CreateUserWalletViewModel(purchaseOrderApplication);

                await _poManager.CreatePurchaseOrderApplication(application);

                await _walletManager.UpdateUserWallet(userWalletVm);

                await transaction.CommitAsync();

                return Ok();
            }
            catch (Exception e)
            {
                await transaction.RollbackAsync();

                return BadRequest();
            }
        }
    }
}

PO Financing/Views/Shared/_Layout.cshtml
@using PO_Financing.Enums
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>@ViewData["Title"]</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Favicons -->
    <link href="../assets/img/LogoIcon.png" rel="icon">
    <link href="../assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,400i,600,700|Raleway:300,400,400i,500,500i,700,800,900" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="../assets/vendor/animate.css/animate.min.css" rel="stylesheet">
    <link href="../assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="../assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="../assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="../assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="../assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">
    <link href="../assets/css/site.css" rel="stylesheet">
    <link href="../assets/vendor/simple-datatables/style.css" rel="stylesheet">
    <link href="../assets/vendor/quill/quill.snow.css" rel="stylesheet">
    <link href="../assets/vendor/quill/quill.bubble.css" rel="stylesheet">
    <!-- Template Main CSS File -->
    <link href="../assets/css/style.css" rel="stylesheet">
</head>
<body>
    <!-- ======= Header ======= -->
    <header id="header" class="fixed-top d-flex align-items-center">
        <div class="container d-flex justify-content-between" id="NavContainer">

            <div class="logo">
                <img src="../assets/img/Logo.png" style="width:120px; max-height:50px;height:50px; cursor:pointer" onclick="NavigateTo('Home')"/>
                <!-- Uncomment below if you prefer to use an image logo -->
                <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
            </div>

            <nav id="navbar" class="navbar">
                <ul>
                    @if (User.IsInRole(UserRole.Admin.GetDisplayName()) || User.IsInRole(UserRole.Client.GetDisplayName()))
                    {
                        <li><a class="nav-link nav-link-default" id="DashboardNav" asp-action="Index" asp-controller="Dashboard">Dashboard</a></li>
                        <li><a class="nav-link nav-link-default" id="POsNav" asp-action="PurchaseOrders" asp-controller="Dashboard">Purchase Orders</a></li>
                        <li><a class="nav-link nav-link-default" id="AccSettingsNav" asp-action="Settings" asp-controller="Account">Account Settings</a></li>
                        <li><a class="nav-link nav-link-default" id="ApplyNav2" asp-action="Apply" asp-controller="Application">Apply</a></li>
                        <li><a class="nav-link nav-link-default" id="LogoutNav" asp-action="Logout" asp-controller="Account">Logout</a></li>
                    }
                    else
                    {
                        <li><a class="nav-link nav-link-default scrollto active" href="#hero">Home</a></li>
                        <li><a class="nav-link nav-link-default scrollto" href="#about">About</a></li>
                        <li><a class="nav-link nav-link-default scrollto" href="#services">Services</a></li>
                        <li><a class="nav-link nav-link-default scrollto" href="#contact">Contact</a></li>
                        <li><a class="nav-link scrollto nav-link-login" asp-action="Login" asp-controller="Account" id="loginNav">Login</a></li>
                        <li><a class="nav-link scrollto nav-link-register" asp-action="Register" asp-controller="Account" id="registerNav">Register</a></li>
                        <li><a class="nav-link scrollto nav-link-apply" asp-action="Apply" asp-controller="Application" id="applyNav">Apply</a></li>
                    }
                </ul>
                <i class="bi bi-list mobile-nav-toggle"></i>
            </nav><!-- .navbar -->

        </div>
    </header><!-- End Header -->

    <div>
        @RenderBody()
    </div>

    <!-- ======= Footer ======= -->
    <footer>
        <div class="footer-area">
            <div class="container">
                <div class="row">
                    <div class="col-md-3">
                        <div class="footer-content">
                            <div class="footer-head">
                                <div class="footer-logo">
                                    <h2><span style="color:#61B834;">P & E</span><span style="color:dodgerblue"> Finance</span></h2>
                                </div>

                                <p style="color:white !important">A company you can trust to assist you with your Purchase Order Financing. </p>
                                <div class="footer-icons">
                                    <ul>
                                        @*<li>
                                            <a href="#"><i class="bi bi-facebook"></i></a>
                                        </li>
                                        <li>
                                            <a href="#"><i class="bi bi-twitter"></i></a>
                                        </li>
                                        <li>
                                            <a href="#"><i class="bi bi-instagram"></i></a>
                                        </li>*@
                                        <li>
                                            <a href="#" style="color:white; border-color:white"><i class="bi bi-linkedin"></i></a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- end single footer -->
                    <div class="col-md-3">
                        <div class="footer-content">
                            <div class="footer-head">
                                <h4 style="color:white">Get In touch</h4>
                                <p style="color:white">
                                    Talk to our experts about your next Purchase Order Funding
                                </p>
                                <div class="footer-contacts">
                                    <p><span>Tel:</span> <span style="color:white !important">+27 73 794 2244</span></p>
                                    <p><span>Email:</span><span style="color:white !important"> info@pnefinance.co.za</span></p>
                                    <p><span>Working Hours:</span> <span style="color:white !important">9am-5pm</span></p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- end single footer -->
                    <div class="col-md-3">
                        <div class="footer-content">
                            <div class="footer-head">
                                <h4 style="color:white">Userful Links</h4>
                                <ul>
                                    <li>> <a class="scrollto" href="#about" style="color:#3EC1D5">About Us</a></li>
                                    <li>> <a class="scrollto" href="#services" style="color:#3EC1D5">Services</a></li>
                                    <li>> <a asp-action="Register" asp-controller="Account" style="color:#3EC1D5">Apply</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="footer-content">
                            <div class="footer-head">
                                <h4 style="color:white">Website Architech</h4>
                                <div>
                                    <div style="display: grid;">
                                        <a class="scrollto credits-font" href="http://www.proficientsoftwaresolutions.co.za">Proficient Software Solutions (Pty) Ltd</a>
                                        <a class="scrollto credits-font" href="http://www.proficientsoftwaresolutions.co.za">www.proficientsoftwaresolutions.co.za</a>
                                        <a class="scrollto credits-font" href="#services">info@proficientsoftwaresolutions.co.za</a>
                                    </div>
                                    <div>
                                        <img src="../Assets/img/ProfSoftwares.png" class="profSoftwaresLogo" onclick="window.location='http://www.proficientsoftwaresolutions.co.za'"/>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-area-bottom">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <div class="copyright text-center">
                            <p style="color:white">
                                &copy; Copyright <strong>P & E Finance</strong>. All Rights Reserved
                            </p>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </footer><!-- End  Footer -->

    <div id="preloader"></div>
    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <script>

        Boot();

        function Boot()
        {
            var loggedUser = '@User.Identity.Name';
            console.log(loggedUser);
            if (loggedUser == '') 
            {
                //$("#NavContainer").addClass('justify-content-between');
                if (localStorage['currentPage'] == 'Login' || localStorage['currentPage'] == 'Register')
                {
                    $(".nav-link-default").hide();
                    $(".footer-area").hide();
                    $("#header").addClass('login-header');
                    $(".footer-area-bottom").css("margin-top","-55px");

                    if (localStorage['currentPage'] == 'Login')
                    {
                        $("#loginNav").hide();
                        $("#applyNav").hide();
                        $("#registerNav").hide();
                    }
                    if (localStorage['currentPage'] == 'Register')
                        $("#registerNav").hide();
                }
                else if (localStorage['currentPage'] == 'Home')
                {
                    $(".nav-link-default").show();
                    $(".footer-area").show();
                    $("#header").removeClass('login-header');
                    $(".footer-area-bottom").css("margin-top", "0");
                }
            }
            else 
            {
                $("#NavContainer").removeClass('justify-content-between');

                $("#DashboardNav").removeClass('active');
                $("#POsNav").removeClass('active');
                $("#AccSettingsNav").removeClass('active');
                $("#ApplyNav2").removeClass('active');

                var activeLink = $("#DashboardNav");

                if(localStorage['currentPage'] == 'Dashboard') activeLink = $("#DashboardNav");
                if(localStorage['currentPage'] == 'Purchase Orders') activeLink = $("#POsNav");
                if(localStorage['currentPage'] == 'Account Settings') activeLink = $("#AccSettingsNav");
                if(localStorage['currentPage'] == 'Apply') activeLink = $("#ApplyNav2");

                activeLink.addClass('active');
                activeLink.addClass('fw-bold');
            }
        }

        function NavigateTo(link)
        {
            var url = "";
            if(link == 'Home')
            {
                url = '@Url.Action("Index","Home")';
            }
            if(link == 'Login')
            {
                url = '@Url.Action("Login","Account")';
            }
            window.location = url;
        }

    </script>
    <!-- Vendor JS Files -->
    <script src="../assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="../assets/vendor/glightbox/js/glightbox.min.js"></script>
    <script src="../assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="../assets/vendor/swiper/swiper-bundle.min.js"></script>
    <script src="../assets/vendor/php-email-form/validate.js"></script>
    <script src="../assets/vendor/quill/quill.min.js"></script>
    <script src="../assets/vendor/simple-datatables/simple-datatables.js"></script>

    <!-- Template Main JS File -->
    <script src="../assets/js/main.js"></script>
    <script src="../assets/js/jquery.js"></script>
    <script src="../assets/js/site.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>